# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration) 
  displayName: dotnet build

#- task: DotNetCoreCLI@2
#  displayName: dotnet publish
#  inputs:
#    command: 'publish'
#    publishWebProjects: false
#    projects: 'src/SimpleAPI/SimpleAPI.csproj'
#    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#    zipAfterPublish: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/SimpleAPI/SimpleAPI.csproj'
    nobuild: true
    buildProperties: '-p:PackageVersion 1.0.0 -p:PackageId SimpleAPI --outupt (Build.ArtifactStagingDirectory)'

- task: Bash@3
  displayName: check files under $(Build.ArtifactStagingDirectory)
  inputs:
    targetType: 'inline'
    script: |
      dir $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
